name: Build Page

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - public/**
      - index.html
      - vite.config.ts

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai # 时区

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install

      - name: Build Page
        run: |
          git pull
          yarn run docs:build
          git pull

      - name: Update GitHub
        run: |
          git config --local user.email "879241805@qq.com"
          git config --local user.name "Anonymity94-Bot"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "ci: build page"
          git push
